version: "3.0"

services:
        nginx:
                build:
                        context: .
                        dockerfile: ./requeriments/nginx/Dockerfile
                ports:
                     - "443:443"
                hostname: nginx

        wordpress:
                 build:
                        context: ./requeriments/wordpress/
                        args:
                            - DB_NAME
                            - DB_USER
                            - DB_PASSWORD
services:
        mariadb:
                build:
                        context: ./requeriments/mariadb/
                        args:
                            - MYSQL_USER
                            - MYSQL_ROOT_PASSWORD
                            - MYSQL_PASSWORD

