version: "3.0"

services:
        #nginx:
                # build:
                        #context: .
                        #dockerfile: ./requeriments/nginx/Dockerfile
                        #  ports:
                        # - "443:443"
                          #                hostname: nginx

        wordpress:
                build:
                        context: .
                        dockerfile: ./requeriments/wordpress/Dockerfile
                environment:
                        DB_NAME: ${DB_NAME}
                        DB_USER: ${DB_USER}
                        DB_PASSWORD: ${DB_PASSWORD}
                hostname: wordpress
