version: "3.0"

services:
        nginx:
                build:
                        context: .
                        dockerfile: ./requeriments/nginx/Dockerfile
                ports:
                     - "443:443"
                hostname: nginx

        wordpress:
                 build:
                        context: ./requeriments/wordpress/
                        args:
                            - DB_NAME
                            - DB_USER
                            - DB_PASSWORD
                 volumes:
                        - wp_vol:/var/www/html/wordpress
 
        mariadb:
                build:
                        context: ./requeriments/mariadb/
                        args:
                            - MYSQL_USER
                            - MYSQL_ROOT_PASSWORD
                            - MYSQL_PASSWORD
                            - MYSQL_DATABASE
                volumes:
                      - db_vol:/var/lib/mysql

                ports:
                     - "3306:3306"

volumes:
        wp_vol:
                driver: local
                driver_opts:
                        o: bind
                        type: none
                        device: /home/$USER/data/wp_vol
        db_vol:
                driver: local
                driver_opts:
                        o: bind
                        type: none
                        device: /home/$USER/data/db_vol


